version: '3.8'
services:
    php-apache:
        container_name: vsnippet-LFI-log-injection-3
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
