version: '3.8'
services:
    php-apache:
        container_name: vsnippet-LFI-to-rce.php-31
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
